# action.yml
name: 'Cobertura Coverage Parser'
description: 'Parses a Cobertura XML coverage report and outputs a Markdown summary'
inputs:
  input:
    description: 'Path to Cobertura XML report file'
    required: false
    default: 'input.xml'
  changeList:
    description: 'Path to changelist'
    required: false
  output:
    description: 'Path to output Markdown file'
    required: false
    default: 'coverage.md'
outputs: {}
runs:
  using: 'docker'
  image: 'docker://ghcr.io/mattiamancina/coverage-report:v1.0.1'
  args:
    - -input
    - ${{ inputs.input }}
    - changeList
    - ${{ inputs.changeList }}
    - -output
    - ${{ inputs.output }}
